koreanbots/core

README.md
=> README.md 오타(?) 수정

README.md
기여 규칙의 링크가 정상적으로 작동되지 않는 현상 수정
=> fix: contributing rule link

pages/api/v2/management/bots/submits/[id]/history.ts, utils/DiscordBot.ts, utils/Query.ts
- Added bot submitted history api.
- Changed bot submission log channel.
=> Chore: improved bot review api

pages/addbot.tsx
hellothisisverification 명령어를 비롯한 인증 관련 가이드를 제거합니다.
=> refactor: remove verification guide

pages/bots/[id]/index.tsx, pages/servers/[id]/index.tsx, pages/users/[id]/index.tsx
서버, 유저, 봇 각각의 프로필 페이지에서 아바타 형태를 개선합니다.
예시)
[ 기존 ]
[ 개선 ]
=> refactor: improve avatar design

pages/bots/[id]/edit.tsx, pages/bots/[id]/index.tsx, pages/bots/[id]/vote.tsx, pages/servers/[id]/edit.tsx, pages/servers/[id]/index.tsx, pages/servers/[id]/vote.tsx, pages/users/[id]/index.tsx
- 아바타 라운딩 작업이 적용되지 않은 페이지들을 수정하였습니다.
- 아래 이미지와 같이 일관성된 디자인을 헤치는 불필요한 공백을 제거합니다.
=> fix: fix unapplied updates

utils/Yup.ts
snowflake 길이가 변경됨에 따른 url 제한을 변경합니다.
=> fix: fix bot url length

pages/addbot.tsx, pages/addserver/index.tsx
=> refactor: add more advertisements

pages/api/v2/bots/[id]/index.ts, pages/api/v2/management/bots/submits/[id]/[date]/deny.ts, utils/DiscordBot.ts, utils/Query.ts
- 공개 심사 거부 로그 채널을 추가합니다. (<#1008376563731013643>)
- 3번 이상 거부된 경우 해당 ID로는 더이상 봇 신청을 할 수 없도록 합니다.
=> feat: add open review deny log and max denies restriction

pages/calculator.tsx, utils/Constants.ts
=> fix: fix overflow from bit calculation

utils/Constants.ts
=> feat: edit wrong color code

pages/addbot.tsx, pages/pendingBots/[id]/[date].tsx
- 카테고리 불일치의 설명에 카테고리 목록에 관한 링크를 추가합니다.
=> feat: add link to category page

package.json
- pipe로 인해 발생하던 문제를 해결합니다.
- start 스크립트가 변경됩니다.
=> fix: resolve issue with piping

utils/Query.ts
- ``bot``스코프의 부재 및 HTTP를 통한 인터렉션만 사용하는 봇들의 프리센스를 **온라인**으로 설정합니다.
=> feat: detect bots using http interactions

components/NSFW.tsx, pages/404.tsx, utils/ShowdownExtensions.ts
https://github.com/twitter/twemoji/issues/580 이슈와 관련해 임시 또는 영구적으로 twemoji CDN을 교체합니다.
=> fix: change twemoji cdn

utils/Query.ts
=> fix: search

utils/Query.ts
- 정렬되지 않아 임의로 봇 혹은 서버가 표시되는 문제를 해결합니다.
=> fix: sort bots with date

components/Footer.tsx
2022 => 2023
추가로 변경해야될 사항이 있다면 이 PR에서 수정해주세요
=> refactor: update footer

utils/Query.ts
=> fix: check bot strikes properly

components/BotCard.tsx, components/ServerCard.tsx
- 봇 혹은 서버 카드의 너비가 줄어들지 않는 않는 문제를 해결합니다. (#478)
=> fix: bot / server card width

pages/api/v2/applications/bots/[id]/index.ts, pages/api/v2/applications/servers/[id]/index.ts, utils/Webhook.ts
- 수정한 url이 반영되지 않을 수 있는 문제를 해결
=> fix: remove outdated webhook client

utils/Webhook.ts
- HTTP 웹후크에 한해 전송 실패 시 10회까지 추가 재전송 시도
=> feat: retry webhook

utils/Webhook.ts
=> fix: webhook retry interval shifted by 1

utils/Webhook.ts
- 실패 문구가 여러번 전송되거나 비활성화된 웹훅으로 요청하는 문제를 수정
=> fix: duplicated failed message

.github/workflows/publish-stable.yml
다음과 같이 새로운 CI 파일을 만들어 적용했습니다.
이제 새로운 릴리즈를 만들면 `stabe` 태그로 이미지를 빌드합니다.
=> feat: add stable tag build

utils/Jwt.ts
- 불필요한 TokenExpiredError 문구가 출력되지 않도록 수정합니다.
=> fix: don't show TokenExpiredError

pages/bots/index.tsx, pages/bots/list/trusted.tsx
- 신뢰된 봇들의 목록을 확인할 수 있는 페이지를 추가합니다.
=> feat: add trusted bots page

pages/api/v1/bots/servers.ts, pages/api/v2/bots/[id]/index.ts, pages/api/v2/bots/[id]/report.ts, pages/api/v2/bots/[id]/stats.ts, pages/api/v2/management/bots/submits/[id]/[date]/approve.ts, pages/api/v2/management/bots/submits/[id]/[date]/deny.ts, pages/api/v2/servers/[id]/report.ts, pages/api/v2/users/[id]/report.ts
=> perf: remove awaits from all internal logging

components/Advertisement.tsx, pages/search.tsx
=> chore: don't show ad on no search result

components/Navbar.tsx
PC 레이아웃 네비게이션바에 적용되어있던 absolute 스타일을 제거하며 Navbar의 UI 버그를 해결하였습니다.
=> fix: PC 레이아웃 네비게이션바 수정
